/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 */

dependencyResolutionManagement {

    versionCatalogs {
        create("libs") {
            version("ktor", "3.1.3")
            version("token-validation-ktor", "5.0.15")
            version("eclipse-angus", "2.0.2")
            version("jsch", "0.2.16")
            version("emottak-utils", "0.3.1")

            library("ktor-server-core", "io.ktor", "ktor-server-core").versionRef("ktor")
            library("ktor-server-netty", "io.ktor", "ktor-server-netty").versionRef("ktor")
            library("ktor-server-content-negotiation", "io.ktor", "ktor-server-content-negotiation").versionRef("ktor")
            library("ktor-client-content-negotiation", "io.ktor", "ktor-client-content-negotiation").versionRef("ktor")
            library("ktor-serialization-kotlinx-json", "io.ktor", "ktor-serialization-kotlinx-json").versionRef("ktor")
            library("ktor-client-core", "io.ktor", "ktor-client-core").versionRef("ktor")
            library("ktor-client-cio", "io.ktor", "ktor-client-cio").versionRef("ktor")
            library("jsch", "com.github.mwiede", "jsch").versionRef("jsch")
            library("ktor-client-auth", "io.ktor", "ktor-client-auth").versionRef("ktor")

            library("ktor-server-metrics-micrometer", "io.ktor", "ktor-server-metrics-micrometer").versionRef("ktor")
            library("micrometer-registry-prometheus", "io.micrometer:micrometer-registry-prometheus:1.12.4")

            library("logback-classic", "ch.qos.logback:logback-classic:1.5.18")
            library("logback-logstash", "net.logstash.logback:logstash-logback-encoder:8.1")

            library("emottak-utils", "no.nav.emottak", "emottak-utils").versionRef("emottak-utils")
            library("ktor-server-auth-jvm", "io.ktor", "ktor-server-auth-jvm").versionRef("ktor")
            library("token-validation-ktor-v3", "no.nav.security", "token-validation-ktor-v3").versionRef("token-validation-ktor")

            bundle("prometheus", listOf("ktor-server-metrics-micrometer", "micrometer-registry-prometheus"))
            bundle("logging", listOf("logback-classic", "logback-logstash"))
        }

        create("testLibs") {
            version("junit", "5.9.2")
            version("hamcrest", "2.2")
            version("mockk", "1.13.10")
            version("xmlunit", "2.9.1")
            version("ktor-server-test", "3.0.3")
            version("kotest", "5.9.1")
            version("kotest-extensions", "2.0.2")
            version("turbine", "1.2.0")
            version("arrow", "2.0.1")

            library("ktor-server-test-host", "io.ktor", "ktor-server-test-host").versionRef("ktor-server-test")
            library("junit-jupiter-api", "org.junit.jupiter", "junit-jupiter-api").versionRef("junit")
            library("junit-jupiter-engine", "org.junit.jupiter", "junit-jupiter-engine").versionRef("junit")
            library("junit-jupiter-params", "org.junit.jupiter", "junit-jupiter-params").versionRef("junit")
            library("mock-oauth2-server", "no.nav.security:mock-oauth2-server:2.1.2")

            library("hamcrest", "org.hamcrest", "hamcrest").versionRef("hamcrest")

            library("mockk-jvm", "io.mockk", "mockk-jvm").versionRef("mockk")
            library("mockk-dsl-jvm", "io.mockk", "mockk-dsl-jvm").versionRef("mockk")

            library("xmlunit-core", "org.xmlunit", "xmlunit-core").versionRef("xmlunit")
            library("xmlunit-matchers", "org.xmlunit", "xmlunit-matchers").versionRef("xmlunit")

            library("kotest-runner-junit5", "io.kotest", "kotest-runner-junit5").versionRef("kotest")
            library("kotest-framework-datatest", "io.kotest", "kotest-framework-datatest").versionRef("kotest")
            library("kotest-extensions-testcontainers", "io.kotest.extensions", "kotest-extensions-testcontainers").versionRef("kotest-extensions")

            library("kotest-assertions-arrow", "io.kotest.extensions", "kotest-assertions-arrow").versionRef("arrow")

            library("turbine", "app.cash.turbine", "turbine").versionRef("turbine")

            bundle("kotest", listOf("kotest-runner-junit5", "kotest-framework-datatest"))
            bundle("mockk", listOf("mockk-jvm", "mockk-dsl-jvm"))
            bundle("xmlunit", listOf("xmlunit-core", "xmlunit-matchers"))
        }
    }

    repositories {
        mavenCentral()
        maven {
            name = "Nav token-support"
            url = uri("https://maven.pkg.github.com/navikt/token-support")
            credentials {
                username = "token"
                password = System.getenv("GITHUB_TOKEN")
            }
        }
        maven {
            name = "Mock OAUTH2 server"
            url = uri("https://maven.pkg.github.com/navikt/mock-oauth2-server")
            credentials {
                username = "token"
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

rootProject.name = "cpa-sync"
// include("cpa-sync")
