/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 */

dependencyResolutionManagement {

    versionCatalogs {
        create("libs") {
            version("ktor", "3.5.1")
            version("exposed", "0.47.0")
            version("jsch", "0.2.16")
            version("emottak-utils", "0.5.0")
            version("micrometer-registry-prometheus", "1.12.4")
            version("logback-classic", "1.5.37")
            version("logback-logstash", "9.0")
            version("nimbus-jose-jwt", "10.9.1")
            version("hikari", "5.0.1")
            version("oracle", "23.26.1.0.0")

            library("ktor-server-core", "io.ktor", "ktor-server-core").versionRef("ktor")
            library("ktor-server-netty", "io.ktor", "ktor-server-netty").versionRef("ktor")
            library("ktor-server-content-negotiation", "io.ktor", "ktor-server-content-negotiation").versionRef("ktor")
            library("ktor-client-content-negotiation", "io.ktor", "ktor-client-content-negotiation").versionRef("ktor")
            library("ktor-serialization-kotlinx-json", "io.ktor", "ktor-serialization-kotlinx-json").versionRef("ktor")
            library("ktor-client-core", "io.ktor", "ktor-client-core").versionRef("ktor")
            library("ktor-client-cio", "io.ktor", "ktor-client-cio").versionRef("ktor")
            library("exposed-jdbc", "org.jetbrains.exposed", "exposed-jdbc").versionRef("exposed")
            library("jsch", "com.github.mwiede", "jsch").versionRef("jsch")
            library("ktor-client-auth", "io.ktor", "ktor-client-auth").versionRef("ktor")

            library("ktor-server-metrics-micrometer", "io.ktor", "ktor-server-metrics-micrometer").versionRef("ktor")
            library("micrometer-registry-prometheus", "io.micrometer", "micrometer-registry-prometheus").versionRef("micrometer-registry-prometheus")

            library("logback-classic", "ch.qos.logback", "logback-classic").versionRef("logback-classic")
            library("logback-logstash", "net.logstash.logback", "logstash-logback-encoder").versionRef("logback-logstash")

            library("emottak-utils", "no.nav.emottak", "emottak-utils").versionRef("emottak-utils")
            library("nimbus-jose-jwt", "com.nimbusds", "nimbus-jose-jwt").versionRef("nimbus-jose-jwt")
            library("hikari", "com.zaxxer", "HikariCP").versionRef("hikari")
            library("oracle", "com.oracle.database.jdbc", "ojdbc8").versionRef("oracle")

            bundle("exposed", listOf("exposed-jdbc"))
            bundle("prometheus", listOf("ktor-server-metrics-micrometer", "micrometer-registry-prometheus"))
            bundle("logging", listOf("logback-classic", "logback-logstash"))
        }

        create("testLibs") {
            version("junit", "5.9.2")
            version("mockk", "1.13.10")

            library("junit-jupiter-api", "org.junit.jupiter", "junit-jupiter-api").versionRef("junit")
            library("junit-jupiter-engine", "org.junit.jupiter", "junit-jupiter-engine").versionRef("junit")

            library("mockk-jvm", "io.mockk", "mockk-jvm").versionRef("mockk")
            library("mockk-dsl-jvm", "io.mockk", "mockk-dsl-jvm").versionRef("mockk")
        }
    }

    repositories {
        mavenCentral()
        maven {
            name = "Nav emottak-utils"
            url = uri("https://maven.pkg.github.com/navikt/emottak-utils")
            credentials {
                username = "token"
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

rootProject.name = "cpa-sync"
