apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "cpa-sync"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
  ingresses:
    - "https://cpa-sync.intern.dev.nav.no"
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/emottak_q1-nmt3
        mountPath: /secret/emottak_db
  filesFrom:
    - secret: cpa-sftp-keys
  env:
    - name: NFS_HOST
      value: b27drvl011.preprod.local
    - name: EMOTTAK_LOGGING_LEVEL
      value: DEBUG
    - name: EMOTTAK_JDBC_URL
      value: jdbc:oracle:thin:@//dmv06-scan.adeo.no:1521/EMOTTAK_Q1_HA
    - name: EMOTTAK_DB_SECRET_PATH
      value: /secret/emottak_db
    - name: ACTIVATE_CPA_INTERVAL
      value: 5m
