apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: team-emottak
  name: ebms-t1-cpasync
  namespace: team-emottak
spec:
  ttlSecondsAfterFinished: 180
  image: {{image}}
  schedule: "*/5 * * * *"
  command:
    - curl
    - http://ebms-t1-cpa-sync/cpa-sync