CREATE SEQUENCE  if not exists PARTNER_CPA_ARCHIVE_SEQ
    MINVALUE 1 MAXVALUE 9999999
    INCREMENT BY 1 START WITH 101 CACHE 20  ;

CREATE TABLE if not exists PARTNER_CPA_ARCHIVE
(	ID NUMBER(10,0) NOT NULL,
     PARTNER_ID NUMBER(10,0) NOT NULL,
     CPA_ID VARCHAR2(50 BYTE) NOT NULL,
     NAV_CPP_ID VARCHAR2(100 BYTE) NOT NULL,
     PARTNER_CPP_ID VARCHAR2(100 BYTE) NOT NULL,
     PARTNER_SUBJECTDN VARCHAR2(1024 BYTE) NOT NULL,
     PARTNER_ENDPOINT VARCHAR2(512 BYTE) NOT NULL,
     CREATED TIMESTAMP (6) NOT NULL,
     MOTTAK_ID VARCHAR2(50 BYTE),
     MAIL_RECEIVER VARCHAR2(1024 BYTE),
     VALID_FROM TIMESTAMP (6) NOT NULL,
     VALID_TO TIMESTAMP (6) NOT NULL,
     CPP CLOB,
     CPA CLOB,
     ISSUER_NONREP VARCHAR2(1024 BYTE) NOT NULL,
     SERIALNO_NONREP VARCHAR2(256 BYTE) NOT NULL,
     VALIDTO_NONREP TIMESTAMP (6) NOT NULL,
     ISSUER_DATAENC VARCHAR2(1024 BYTE) NOT NULL,
     SERIALNO_DATAENC VARCHAR2(256 BYTE) NOT NULL,
     VALIDTO_DATAENC TIMESTAMP (6) NOT NULL,
     ISSUER_SSL VARCHAR2(1024 BYTE),
     SERIALNO_SSL VARCHAR2(256 BYTE),
     VALIDTO_SSL TIMESTAMP (6),
     DELETED NUMBER(1,0),
     CREATED_BY VARCHAR2(50 BYTE),
     QUARANTINED NUMBER(1,0),
     REASON VARCHAR2(512 BYTE),
     CONSTRAINT PARTNER_CPA_ID PRIMARY KEY (ID)
) ;

CREATE TABLE if not exists PARTNER_CPA
(	CPA_ID VARCHAR2(50 BYTE) NOT NULL,
     PARTNER_ID NUMBER(10,0) NOT NULL,
     NAV_CPP_ID VARCHAR2(100 BYTE) NOT NULL,
     PARTNER_CPP_ID VARCHAR2(100 BYTE) NOT NULL,
     PARTNER_SUBJECTDN VARCHAR2(1024 BYTE) NOT NULL,
     PARTNER_ENDPOINT VARCHAR2(512 BYTE) NOT NULL,
     LASTUSED TIMESTAMP (6),
    CONSTRAINT CPA_ID PRIMARY KEY (CPA_ID)
);